export enum VillageCategory {
  Category1 = 'category1',
  Category2 = 'category2',
}

export enum VillageCategoryLabel {
  Category1 = 'Category 1',
  Category2 = 'Category 2',
}

export const villageCategoryOptions = [
  { value: VillageCategory.Category1, label: 'Category 1' },
  { value: VillageCategory.Category2, label: 'Category 2' },
];

// Complete South Sumatra Location Constants based on kodewilayah.id
export const PROVINCE_CODE = '16';
export const PROVINCE_NAME = 'Sumatera Selatan';

export const southSumatraRegencies = [
  {
    code: '16.02',
    name: 'Kabupaten Ogan Komering Ilir',
    capital: 'Kayu Agung',
    type: 'regency',
  },
  {
    code: '16.05',
    name: 'Kabupaten Musi Rawas',
    capital: 'Muara Beliti',
    type: 'regency',
  },
  {
    code: '16.06',
    name: 'Kabupaten Musi Banyuasin',
    capital: 'Sekayu',
    type: 'regency',
  },
  {
    code: '16.07',
    name: 'Kabupaten Banyuasin',
    capital: 'Pangkalan Balai',
    type: 'regency',
  },
  {
    code: '16.08',
    name: 'Kabupaten Ogan Komering Ulu Timur',
    capital: 'Martapura',
    type: 'regency',
  },
  {
    code: '16.10',
    name: 'Kabupaten Ogan Ilir',
    capital: 'Indralaya',
    type: 'regency',
  },
  {
    code: '16.11',
    name: 'Kabupaten Empat Lawang',
    capital: 'Tebing Tinggi',
    type: 'regency',
  },
  {
    code: '16.12',
    name: 'Kabupaten Penukal Abab Lematang Ilir',
    capital: 'Talang Ubi',
    type: 'regency',
  },
  {
    code: '16.13',
    name: 'Kabupaten Musi Rawas Utara',
    capital: 'Rupit',
    type: 'regency',
  },

  // Cities (Kota)
  {
    code: '16.74',
    name: 'Kota Prabumulih',
    capital: 'Prabumulih',
    type: 'city',
  },
];

// Village data organized by categories from CSV files
export interface Village {
  no: number;
  code: string;
  name: string;
  kecamatan: string;
  kabupaten: string;
  category: VillageCategory;
  type: string;
}

export const category1Villages: Village[] = [
  {
    no: 1,
    code: '16.74.02.1011',
    name: 'Kelurahan Gunung Ibul Utara',
    kecamatan: 'Prabumulih Timur',
    kabupaten: 'Kota Prabumulih',
    category: VillageCategory.Category1,
    type: 'kelurahan',
  },
  {
    no: 2,
    code: '16.74.02.1010',
    name: 'Kelurahan Karang Jaya',
    kecamatan: 'Prabumulih Timur',
    kabupaten: 'Kota Prabumulih',
    category: VillageCategory.Category1,
    type: 'kelurahan',
  },
  {
    no: 3,
    name: 'Kelurahan Gunung Kemala',
    code: '16.74.01.1011',
    kecamatan: 'Prabumulih Barat',
    kabupaten: 'Kota Prabumulih',
    category: VillageCategory.Category1,
    type: 'kelurahan',
  },
  {
    no: 4,
    code: '16.74.01.2014',
    name: 'Tebing Tanah Puteh Village',
    kecamatan: 'Prabumulih Barat',
    kabupaten: 'Kota Prabumulih',
    category: VillageCategory.Category1,
    type: 'desa',
  },
  {
    no: 5,
    code: '16.74.05.1003',
    name: 'Kelurahan Wonosari',
    kecamatan: 'Prabumulih Utara',
    kabupaten: 'Kota Prabumulih',
    category: VillageCategory.Category1,
    type: 'kelurahan',
  },
  {
    no: 6,
    code: '16.74.01.1012',
    name: 'Kelurahan Payu putat',
    kecamatan: 'Prabumulih Barat',
    kabupaten: 'Kota Prabumulih',
    category: VillageCategory.Category1,
    type: 'kelurahan',
  },
  {
    no: 7,
    code: '16.74.01.1009',
    name: 'Kelurahan Muntang Tapus',
    kecamatan: 'Prabumulih Barat',
    kabupaten: 'Kota Prabumulih',
    category: VillageCategory.Category1,
    type: 'kelurahan',
  },
  {
    no: 8,
    code: '16.74.06.2004',
    name: 'Kelurahan Tanjung Menang',
    kecamatan: 'Prabumulih Selatan',
    kabupaten: 'Kota Prabumulih',
    category: VillageCategory.Category1,
    type: 'kelurahan',
  },
  {
    no: 9,
    code: '16.10.10.2006',
    name: 'Ulak Kembahang 1 Village',
    kecamatan: 'Pemulutan Barat',
    kabupaten: 'Kabupaten Ogan Ilir',
    category: VillageCategory.Category1,
    type: 'desa',
  },
  {
    no: 10,
    code: '16.10.10.2009',
    name: 'Ulak Kembahang 2 Village',
    kecamatan: 'Pemulutan Barat',
    kabupaten: 'Kabupaten Ogan Ilir',
    category: VillageCategory.Category1,
    type: 'desa',
  },
  {
    no: 11,
    code: '16.10.10.2004',
    name: 'Pulau Negara Village',
    kecamatan: 'Pemulutan Barat',
    kabupaten: 'Kabupaten Ogan Ilir',
    category: VillageCategory.Category1,
    type: 'desa',
  },
  {
    no: 12,
    code: '16.10.03.2008',
    name: 'Seri Dalam Village',
    kecamatan: 'Tanjung Raja',
    kabupaten: 'Kabupaten Ogan Ilir',
    category: VillageCategory.Category1,
    type: 'desa',
  },
  {
    no: 13,
    code: '16.10.07.2010',
    name: 'Tanjung Pule Village',
    kecamatan: 'Indralaya Utara',
    kabupaten: 'Kabupaten Ogan Ilir',
    category: VillageCategory.Category1,
    type: 'desa',
  },
  {
    no: 14,
    code: '16.10.14.2011',
    name: 'Sunur Village',
    kecamatan: 'Rambang Kuang',
    kabupaten: 'Kabupaten Ogan Ilir',
    category: VillageCategory.Category1,
    type: 'desa',
  },
  {
    no: 15,
    code: '16.10.10.2011',
    name: 'Arisan Jaya Village',
    kecamatan: 'Pemulutan Barat',
    kabupaten: 'Kabupaten Ogan Ilir',
    category: VillageCategory.Category1,
    type: 'desa',
  },
  {
    no: 16,
    code: '16.10.07.2013',
    name: 'Pulau Kabal Village',
    kecamatan: 'Indralaya Utara',
    kabupaten: 'Kabupaten Ogan Ilir',
    category: VillageCategory.Category1,
    type: 'desa',
  },
  {
    no: 17,
    code: '16.10.10.2007',
    name: 'Ulak Petangisan Village',
    kecamatan: 'Pemulutan Barat',
    kabupaten: 'Kabupaten Ogan Ilir',
    category: VillageCategory.Category1,
    type: 'desa',
  },
  {
    no: 18,
    code: '16.12.05.2006',
    name: 'Curup Village',
    kecamatan: 'Tanah Abang',
    kabupaten: 'Kabupaten Penukal Abab Lematang Ilir',
    category: VillageCategory.Category1,
    type: 'desa',
  },
  {
    no: 19,
    code: '16.12.04.2006',
    name: 'Prambatan Village',
    kecamatan: 'Abab',
    kabupaten: 'Kabupaten Penukal Abab Lematang Ilir',
    category: VillageCategory.Category1,
    type: 'desa',
  },
  {
    no: 20,
    code: '16.12.01.2005',
    name: 'Sungai Ibul Village',
    kecamatan: 'Talang Ubi',
    kabupaten: 'Kabupaten Penukal Abab Lematang Ilir',
    category: VillageCategory.Category1,
    type: 'desa',
  },
  {
    no: 21,
    code: '16.12.01.2016',
    name: 'Suka Damai Village',
    kecamatan: 'Talang Ubi',
    kabupaten: 'Kabupaten Penukal Abab Lematang Ilir',
    category: VillageCategory.Category1,
    type: 'desa',
  },
  {
    no: 22,
    code: '16.12.05.2004',
    name: 'Sedupi Village',
    kecamatan: 'Tanah Abang',
    kabupaten: 'Kabupaten Penukal Abab Lematang Ilir',
    category: VillageCategory.Category1,
    type: 'desa',
  },
  {
    no: 23,
    code: '16.12.01.1017',
    name: 'Kelurahan Pasar Bhayangkara',
    kecamatan: 'Talang Ubi',
    kabupaten: 'Kabupaten Penukal Abab Lematang Ilir',
    category: VillageCategory.Category1,
    type: 'kelurahan',
  },
  {
    no: 24,
    code: '16.12.04.2003',
    name: 'Karang Agung Village',
    kecamatan: 'Abab',
    kabupaten: 'Kabupaten Penukal Abab Lematang Ilir',
    category: VillageCategory.Category1,
    type: 'desa',
  },
  {
    no: 25,
    code: '16.12.01.1003',
    name: 'Kelurahan Talang Ubi Timur',
    kecamatan: 'Talang Ubi',
    kabupaten: 'Kabupaten Penukal Abab Lematang Ilir',
    category: VillageCategory.Category1,
    type: 'kelurahan',
  },
  {
    no: 26,
    code: '16.12.01.2015',
    name: 'Suka Maju Village',
    kecamatan: 'Talang Ubi',
    kabupaten: 'Kabupaten Penukal Abab Lematang Ilir',
    category: VillageCategory.Category1,
    type: 'desa',
  },
  {
    no: 27,
    code: '16.05.01.2007',
    name: 'Wonokerto Village',
    kecamatan: 'Tugumulyo',
    kabupaten: 'Kabupaten Musi Rawas',
    category: VillageCategory.Category1,
    type: 'desa',
  },
  {
    no: 28,
    code: '16.05.13.2008',
    name: 'Rejo Sari Village',
    kecamatan: 'Purwodadi',
    kabupaten: 'Kabupaten Musi Rawas',
    category: VillageCategory.Category1,
    type: 'desa',
  },
  {
    no: 29,
    code: '16.05.19.2001',
    name: 'Sumber Jaya Village',
    kecamatan: 'Sumber Harta',
    kabupaten: 'Kabupaten Musi Rawas',
    category: VillageCategory.Category1,
    type: 'desa',
  },
  {
    no: 30,
    code: '16.05.13.2004',
    name: 'Mardi harjo Village',
    kecamatan: 'Purwodadi',
    kabupaten: 'Kabupaten Musi Rawas',
    category: VillageCategory.Category1,
    type: 'desa',
  },
  {
    no: 31,
    code: '16.05.13.2010',
    name: 'Purwakarya Village',
    kecamatan: 'Purwodadi',
    kabupaten: 'Kabupaten Musi Rawas',
    category: VillageCategory.Category1,
    type: 'desa',
  },
  {
    no: 32,
    code: '16.05.12.2016',
    name: 'Wonosari Village',
    kecamatan: 'Megang Sakti',
    kabupaten: 'Kabupaten Musi Rawas',
    category: VillageCategory.Category1,
    type: 'desa',
  },
  {
    no: 33,
    code: '16.05.01.2011',
    name: 'Ngadirejo Village',
    kecamatan: 'Tugumulyo',
    kabupaten: 'Kabupaten Musi Rawas',
    category: VillageCategory.Category1,
    type: 'desa',
  },
  {
    no: 34,
    code: '16.05.03.2022',
    name: 'Petrans Jaya Village',
    kecamatan: 'Muara Kelingi',
    kabupaten: 'Kabupaten Musi Rawas',
    category: VillageCategory.Category1,
    type: 'desa',
  },
  {
    no: 35,
    code: '16.05.12.2005',
    name: 'Megang Sakti IV Village',
    kecamatan: 'Megang Sakti',
    kabupaten: 'Kabupaten Musi Rawas',
    category: VillageCategory.Category1,
    type: 'desa',
  },
  {
    no: 36,
    code: '16.11.08.2005',
    name: 'Karang Dapo Baru Village',
    kecamatan: 'Sikap Dalam',
    kabupaten: 'Kabupaten Empat Lawang',
    category: VillageCategory.Category1,
    type: 'desa',
  },
  {
    no: 37,
    code: '16.11.03.2025',
    name: 'Galang Village',
    kecamatan: 'Ulu Musi',
    kabupaten: 'Kabupaten Empat Lawang',
    category: VillageCategory.Category1,
    type: 'desa',
  },
  {
    no: 38,
    code: '16.11.03.2004',
    name: 'Simpang Perigi Village',
    kecamatan: 'Ulu Musi',
    kabupaten: 'Kabupaten Empat Lawang',
    category: VillageCategory.Category1,
    type: 'desa',
  },
  {
    no: 39,
    code: '16.11.03.2005',
    name: 'Muara Kalangan Village',
    kecamatan: 'Ulu Musi',
    kabupaten: 'Kabupaten Empat Lawang',
    category: VillageCategory.Category1,
    type: 'desa',
  },
  {
    no: 40,
    code: '16.11.02.2023',
    name: 'Landur Village',
    kecamatan: 'Pendopo',
    kabupaten: 'Kabupaten Empat Lawang',
    category: VillageCategory.Category1,
    type: 'desa',
  },
  {
    no: 41,
    code: '16.11.02.2022',
    name: 'Gunung Meraksa Baru Village',
    kecamatan: 'Pendopo',
    kabupaten: 'Kabupaten Empat Lawang',
    category: VillageCategory.Category1,
    type: 'desa',
  },
  {
    no: 42,
    code: '16.11.02.2029',
    name: 'Gunung Meraksa Lama Village',
    kecamatan: 'Pendopo',
    kabupaten: 'Kabupaten Empat Lawang',
    category: VillageCategory.Category1,
    type: 'desa',
  },
  {
    no: 43,
    code: '16.11.02.1030',
    name: 'Kelurahan Pendopo',
    kecamatan: 'Pendopo',
    kabupaten: 'Kabupaten Empat Lawang',
    category: VillageCategory.Category1,
    type: 'kelurahan',
  },
  {
    no: 44,
    code: '16.11.10.2005',
    name: 'Tanjung Raya Village',
    kecamatan: 'Pendopo Barat',
    kabupaten: 'Kabupaten Empat Lawang',
    category: VillageCategory.Category1,
    type: 'desa',
  },
  {
    no: 45,
    code: '16.06.09.2017',
    name: 'Suka Jaya Village',
    kecamatan: 'Bayung Lencir',
    kabupaten: 'Kabupaten Musi Banyuasin',
    category: VillageCategory.Category1,
    type: 'desa',
  },
  {
    no: 46,
    code: '16.06.12.2003',
    name: 'Berlian Jaya Village',
    kecamatan: 'Tungkal Jaya',
    kabupaten: 'Kabupaten Musi Banyuasin',
    category: VillageCategory.Category1,
    type: 'desa',
  },
  {
    no: 47,
    code: '16.06.09.2026',
    name: 'Senawar Jaya Village',
    kecamatan: 'Bayung Lencir',
    kabupaten: 'Kabupaten Musi Banyuasin',
    category: VillageCategory.Category1,
    type: 'desa',
  },
  {
    no: 48,
    code: '16.06.09.20631',
    name: 'Lubuk Harjo Village Dusun 1',
    kecamatan: 'Bayung Lencir',
    kabupaten: 'Kabupaten Musi Banyuasin',
    category: VillageCategory.Category1,
    type: 'desa',
  },
  {
    no: 49,
    code: '16.06.09.20632',
    name: 'Lubuk Harjo Village Dusun 2',
    kecamatan: 'Bayung Lencir',
    kabupaten: 'Kabupaten Musi Banyuasin',
    category: VillageCategory.Category1,
    type: 'desa',
  },
  {
    no: 50,
    code: '16.06.03.2014',
    name: 'Kerta Jaya Village',
    kecamatan: 'Sungai Keruh',
    kabupaten: 'Kabupaten Musi Banyuasin',
    category: VillageCategory.Category1,
    type: 'desa',
  },
  {
    no: 51,
    code: '16.06.05.2012',
    name: 'Tanjung Raya Village',
    kecamatan: 'Sanga Desa',
    kabupaten: 'Kabupaten Musi Banyuasin',
    category: VillageCategory.Category1,
    type: 'desa',
  },
  {
    no: 52,
    code: '16.06.05.2002',
    name: 'Nganti Village',
    kecamatan: 'Sanga Desa',
    kabupaten: 'Kabupaten Musi Banyuasin',
    category: VillageCategory.Category1,
    type: 'desa',
  },
  {
    no: 53,
    code: '16.06.04.2004',
    name: 'Talang Leban Village',
    kecamatan: 'Batanghari Leko',
    kabupaten: 'Kabupaten Musi Banyuasin',
    category: VillageCategory.Category1,
    type: 'desa',
  },
  {
    no: 54,
    code: '16.13.05.2003',
    name: 'Biaro Lama Village',
    kecamatan: 'Karang Dapo',
    kabupaten: 'Kabupaten Musi Rawas Utara',
    category: VillageCategory.Category1,
    type: 'desa',
  },
  {
    no: 55,
    code: '16.13.02.2009',
    name: 'Surulangun Village',
    kecamatan: 'Rawas Ulu',
    kabupaten: 'Kabupaten Musi Rawas Utara',
    category: VillageCategory.Category1,
    type: 'desa',
  },
  {
    no: 56,
    code: '16.13.02.2014',
    name: 'Simpang Nibung Rawas Village',
    kecamatan: 'Rawas Ulu',
    kabupaten: 'Kabupaten Musi Rawas Utara',
    category: VillageCategory.Category1,
    type: 'desa',
  },
  {
    no: 57,
    code: '16.13.02.2015',
    name: 'Lubuk Mas Village',
    kecamatan: 'Rawas Ulu',
    kabupaten: 'Kabupaten Musi Rawas Utara',
    category: VillageCategory.Category1,
    type: 'desa',
  },
  {
    no: 58,
    code: '16.13.02.2008',
    name: 'Sungai Kijang Village',
    kecamatan: 'Rawas Ulu',
    kabupaten: 'Kabupaten Musi Rawas Utara',
    category: VillageCategory.Category1,
    type: 'desa',
  },
  {
    no: 59,
    code: '16.13.05.2008',
    name: 'Setia Marga Village',
    kecamatan: 'Karang Dapo',
    kabupaten: 'Kabupaten Musi Rawas Utara',
    category: VillageCategory.Category1,
    type: 'desa',
  },
  {
    no: 60,
    code: '16.13.02.2003',
    name: 'Teladas Village',
    kecamatan: 'Rawas Ulu',
    kabupaten: 'Kabupaten Musi Rawas Utara',
    category: VillageCategory.Category1,
    type: 'desa',
  },
  {
    no: 61,
    code: '16.13.02.2002',
    name: 'Kerta Dewa Village',
    kecamatan: 'Rawas Ulu',
    kabupaten: 'Kabupaten Musi Rawas Utara',
    category: VillageCategory.Category1,
    type: 'desa',
  },
  {
    no: 62,
    code: '16.13.02.2007',
    name: 'Sungai Jauh Village',
    kecamatan: 'Rawas Ulu',
    kabupaten: 'Kabupaten Musi Rawas Utara',
    category: VillageCategory.Category1,
    type: 'desa',
  },
  {
    no: 63,
    code: '16.08.02.2033',
    name: 'Kurungan Nyawa III Village',
    kecamatan: 'Buay Madang',
    kabupaten: 'Kabupaten Ogan Komering Ulu Timur',
    category: VillageCategory.Category1,
    type: 'desa',
  },
  {
    no: 64,
    code: '16.08.16.2001',
    name: 'Jayapura Village',
    kecamatan: 'Jayapura',
    kabupaten: 'Kabupaten Ogan Komering Ulu Timur',
    category: VillageCategory.Category1,
    type: 'desa',
  },
  {
    no: 65,
    code: '16.08.02.2001',
    name: 'Sukaraja Village',
    kecamatan: 'Buay Madang',
    kabupaten: 'Kabupaten Ogan Komering Ulu Timur',
    category: VillageCategory.Category1,
    type: 'desa',
  },
  {
    no: 66,
    code: '16.08.02.2031',
    name: 'Kurungan Nyawa I Village',
    kecamatan: 'Buay Madang',
    kabupaten: 'Kabupaten Ogan Komering Ulu Timur',
    category: VillageCategory.Category1,
    type: 'desa',
  },
  {
    no: 67,
    code: '16.08.02.2032',
    name: 'Kurungan Nyawa II Village',
    kecamatan: 'Buay Madang',
    kabupaten: 'Kabupaten Ogan Komering Ulu Timur',
    category: VillageCategory.Category1,
    type: 'desa',
  },
  {
    no: 68,
    code: '16.08.02.2002',
    name: 'Kurungan Nyawa Village',
    kecamatan: 'Buay Madang',
    kabupaten: 'Kabupaten Ogan Komering Ulu Timur',
    category: VillageCategory.Category1,
    type: 'desa',
  },
  {
    no: 69,
    code: '16.08.05.2007',
    name: 'Trantang Sakti Village',
    kecamatan: 'Buay Pemuka Peliung',
    kabupaten: 'Kabupaten Ogan Komering Ulu Timur',
    category: VillageCategory.Category1,
    type: 'desa',
  },
  {
    no: 70,
    code: '16.08.05.2008',
    name: 'Pemetung Basuki Village',
    kecamatan: 'Buay Pemuka Peliung',
    kabupaten: 'Kabupaten Ogan Komering Ulu Timur',
    category: VillageCategory.Category1,
    type: 'desa',
  },
  {
    no: 71,
    code: '16.08.02.2036',
    name: 'Sukaraja Tuha Village',
    kecamatan: 'Buay Madang',
    kabupaten: 'Kabupaten Ogan Komering Ulu Timur',
    category: VillageCategory.Category1,
    type: 'desa',
  },
  {
    no: 72,
    code: '16.07.03.2021',
    name: 'Tanjung Menang Village',
    kecamatan: 'Banyuasin III',
    kabupaten: 'Kabupaten Banyuasin',
    category: VillageCategory.Category1,
    type: 'desa',
  },
  {
    no: 73,
    code: '16.07.17.2009',
    name: 'Limbang Mulya Village',
    kecamatan: 'Sembawa',
    kabupaten: 'Kabupaten Banyuasin',
    category: VillageCategory.Category1,
    type: 'desa',
  },
  {
    no: 74,
    code: '16.07.02.2019',
    name: 'Muara Sungsang Village',
    kecamatan: 'Banyuasin II',
    kabupaten: 'Kabupaten Banyuasin',
    category: VillageCategory.Category1,
    type: 'desa',
  },
  {
    no: 75,
    code: '16.07.05.2004',
    name: 'Sri Kembang Village',
    kecamatan: 'Betung',
    kabupaten: 'Kabupaten Banyuasin',
    category: VillageCategory.Category1,
    type: 'desa',
  },
  {
    no: 76,
    code: '16.07.06.2006',
    name: 'Suka Pindah Village',
    kecamatan: 'Rambutan',
    kabupaten: 'Kabupaten Banyuasin',
    category: VillageCategory.Category1,
    type: 'desa',
  },
  {
    no: 77,
    code: '16.07.04.2002',
    name: 'Teluk Betung Village',
    kecamatan: 'Pulau Rimau',
    kabupaten: 'Kabupaten Banyuasin',
    category: VillageCategory.Category1,
    type: 'desa',
  },
  {
    no: 78,
    code: '16.07.12.2012',
    name: 'Sumber Mekar Mukti Village',
    kecamatan: 'Tanjung Lago',
    kabupaten: 'Kabupaten Banyuasin',
    category: VillageCategory.Category1,
    type: 'desa',
  },
  {
    no: 79,
    code: '16.07.12.2015',
    name: 'Bunga Karang Village',
    kecamatan: 'Tanjung Lago',
    kabupaten: 'Kabupaten Banyuasin',
    category: VillageCategory.Category1,
    type: 'desa',
  },
  {
    no: 80,
    code: '16.02.11.2002',
    name: 'Pulau Beruang Village',
    kecamatan: 'Tulung Selapan',
    kabupaten: 'Kabupaten Ogan Komering Ilir',
    category: VillageCategory.Category1,
    type: 'desa',
  },
  {
    no: 81,
    code: '16.02.15.2009',
    name: 'Talang Jaya Village',
    kecamatan: 'Sungai Menang',
    kabupaten: 'Kabupaten Ogan Komering Ilir',
    category: VillageCategory.Category1,
    type: 'desa',
  },
  {
    no: 82,
    code: '16.02.15.2001',
    name: 'Sungai Menang Village',
    kecamatan: 'Sungai Menang',
    kabupaten: 'Kabupaten Ogan Komering Ilir',
    category: VillageCategory.Category1,
    type: 'desa',
  },
  {
    no: 83,
    code: '16.02.24.2001',
    name: 'Pulau Geronggang Village Dusun 7',
    kecamatan: 'Pedamaran Timur',
    kabupaten: 'Kabupaten Ogan Komering Ilir',
    category: VillageCategory.Category1,
    type: 'desa',
  },
  {
    no: 84,
    code: '16.02.11.2008',
    name: 'Petaling Village',
    kecamatan: 'Tulung Selapan',
    kabupaten: 'Kabupaten Ogan Komering Ilir',
    category: VillageCategory.Category1,
    type: 'desa',
  },
  {
    no: 85,
    code: '16.02.11.2007',
    name: 'Kayu Aro Village',
    kecamatan: 'Tulung Selapan',
    kabupaten: 'Kabupaten Ogan Komering Ilir',
    category: VillageCategory.Category1,
    type: 'desa',
  },
  {
    no: 86,
    code: '16.02.12.2017',
    name: 'Jungkal Village',
    kecamatan: 'Pampangan',
    kabupaten: 'Kabupaten Ogan Komering Ilir',
    category: VillageCategory.Category1,
    type: 'desa',
  },
  {
    no: 87,
    code: '16.02.11.2012',
    name: 'Lebung Itam Village',
    kecamatan: 'Tulung Selapan',
    kabupaten: 'Kabupaten Ogan Komering Ilir',
    category: VillageCategory.Category1,
    type: 'desa',
  },
  {
    no: 88,
    code: '16.02.24.2007',
    name: 'Kayu Labu Village',
    kecamatan: 'Pedamaran Timur',
    kabupaten: 'Kabupaten Ogan Komering Ilir',
    category: VillageCategory.Category1,
    type: 'desa',
  },
];

// Category 2 Villages (from Villlage - Cat 2.csv)
export const category2Villages: Village[] = [
  {
    no: 89,
    code: '16.74.02.1006',
    name: 'Kelurahan Muara Dua',
    kecamatan: 'Prabumulih Timur',
    kabupaten: 'Kota Prabumulih',
    category: VillageCategory.Category2,
    type: 'kelurahan',
  },
  {
    no: 90,
    code: '16.74.02.1003',
    name: 'Karang Raja Village',
    kecamatan: 'Prabumulih Timur',
    kabupaten: 'Kota Prabumulih',
    category: VillageCategory.Category2,
    type: 'desa',
  },
  {
    no: 91,
    code: '16.10.05.2017',
    name: 'Muara Dua Village',
    kecamatan: 'Pemulutan',
    kabupaten: 'Kabupaten Ogan Ilir',
    category: VillageCategory.Category2,
    type: 'desa',
  },
  {
    no: 92,
    code: '16.12.05.2008',
    name: 'Pandan Village',
    kecamatan: 'Tanah Abang',
    kabupaten: 'Kabupaten Penukal Abab Lematang Ilir',
    category: VillageCategory.Category2,
    type: 'desa',
  },
  {
    no: 93,
    code: '16.05.13.2009',
    name: 'Sadar Karya Village',
    kecamatan: 'Purwodadi',
    kabupaten: 'Kabupaten Musi Rawas',
    category: VillageCategory.Category2,
    type: 'desa',
  },
  {
    no: 94,
    code: '16.11.03.2007',
    name: 'Padang Tepong Village',
    kecamatan: 'Ulu Musi',
    kabupaten: 'Kabupaten Empat Lawang',
    category: VillageCategory.Category2,
    type: 'desa',
  },
  {
    no: 95,
    code: '16.06.09.2058',
    name: 'Mekar Jaya Village',
    kecamatan: 'Bayung Lencir',
    kabupaten: 'Kabupaten Musi Banyuasin',
    category: VillageCategory.Category2,
    type: 'desa',
  },
  {
    no: 96,
    code: '16.13.02.2013',
    name: 'Lesung Batu Muda Village',
    kecamatan: 'Rawas Ulu',
    kabupaten: 'Kabupaten Musi Rawas Utara',
    category: VillageCategory.Category2,
    type: 'desa',
  },
  {
    no: 97,
    code: '16.08.05.2006',
    name: 'Saung Dadi Village',
    kecamatan: 'Buay Pemuka Peliung',
    kabupaten: 'Kabupaten Ogan Komering Ulu Timur',
    category: VillageCategory.Category2,
    type: 'desa',
  },
  {
    no: 98,
    code: '16.07.03.2022',
    name: 'Sri Bandung Village',
    kecamatan: 'Banyuasin III',
    kabupaten: 'Kabupaten Banyuasin',
    category: VillageCategory.Category2,
    type: 'desa',
  },
  {
    no: 99,
    code: '16.07.06.2016',
    name: 'Sungai Pinang Village',
    kecamatan: 'Rambutan',
    kabupaten: 'Kabupaten Banyuasin',
    category: VillageCategory.Category2,
    type: 'desa',
  },
  {
    no: 100,
    code: '16.02.03.2018',
    name: 'Suka Pulih Village',
    kecamatan: 'Pedamaran',
    kabupaten: 'Kabupaten Ogan Komering Ilir',
    category: VillageCategory.Category2,
    type: 'desa',
  },
];

// All villages combined
export const allVillages: Village[] = [
  ...category1Villages,
  ...category2Villages,
];

// Helper function to get villages by category
export const getVillagesByCategory = (category: VillageCategory): Village[] => {
  return allVillages.filter((village) => village.category === category);
};

// Helper function to get villages by kabupaten
export const getVillagesByKabupaten = (kabupaten: string): Village[] => {
  return allVillages.filter((village) => village.kabupaten === kabupaten);
};

// Helper function to get villages by kecamatan
export const getVillagesByKecamatan = (kecamatan: string): Village[] => {
  return allVillages.filter((village) => village.kecamatan === kecamatan);
};

// Legacy support - keeping old structure for backward compatibility
// Generated from allVillages data
export const villagesByRegency: Record<
  string,
  Array<{ code: string; name: string; type: 'desa' | 'kelurahan' }>
> = (() => {
  const regencyMap: Record<string, string> = {
    'Kabupaten Ogan Komering Ilir': '16.02',
    'Kabupaten Musi Rawas': '16.05',
    'Kabupaten Musi Banyuasin': '16.06',
    'Kabupaten Banyuasin': '16.07',
    'Kabupaten Ogan Komering Ulu Timur': '16.08',
    'Kabupaten Ogan Ilir': '16.10',
    'Kabupaten Empat Lawang': '16.11',
    'Kabupaten Penukal Abab Lematang Ilir': '16.12',
    'Kabupaten Musi Rawas Utara': '16.13',
    'Kota Prabumulih': '16.74',
  };

  const result: Record<
    string,
    Array<{ code: string; name: string; type: 'desa' | 'kelurahan' }>
  > = {};

  allVillages.forEach((village) => {
    const regencyCode = regencyMap[village.kabupaten];
    if (regencyCode && village.code && village.type) {
      if (!result[regencyCode]) {
        result[regencyCode] = [];
      }
      result[regencyCode].push({
        code: village.code,
        name: village.name,
        type: village.type as 'desa' | 'kelurahan',
      });
    }
  });

  return result;
})();
